// Merge verified track files, keep only rows whose real Spotify title matches
// the intended song, then emit hitster/songs.js as browser globals.
//   window.HITSTER_TEST  -> curated 10-card deck for first-play verification
//   window.HITSTER_FULL  -> every verified track (used after verification)
// Usage: node hitster/tools/build-songs.mjs

import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const songsOut = join(here, "..", "songs.js");

const norm = (s) =>
  (s || "")
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9]+/g, " ")
    .trim();

async function loadVerified(name) {
  try {
    return JSON.parse(await readFile(join(here, name), "utf8"));
  } catch {
    return [];
  }
}

const raw = [...(await loadVerified("verified.json")), ...(await loadVerified("verified2.json"))];

const kept = [];
const dropped = [];
const seen = new Set();
for (const t of raw) {
  if (seen.has(t.id)) continue;
  seen.add(t.id);
  const matches = norm(t.spotifyTitle).includes(norm(t.title));
  if (matches) kept.push(t);
  else dropped.push(t);
}

kept.sort((a, b) => a.year - b.year || a.artist.localeCompare(b.artist));

const song = (t) => ({
  id: t.id,
  title: t.title,
  artist: t.artist,
  year: t.year,
  url: `https://open.spotify.com/track/${t.id}`,
});

const full = kept.map(song);

// Curated 10-card test deck: a wide spread across the decades.
const testIds = [
  "5CQ30WqJwcep0pYcV4AMNc", // 1971 Led Zeppelin
  "0GjEhVFGZW8afUYGChu3Rr", // 1976 ABBA
  "5ChkMS8OtdzJeqyybCc9R5", // 1982 Michael Jackson
  "2WfaOiMkCvy7F5fcp2zZ8L", // 1985 a-ha
  "4cOdK2wGLETKBW3PvgPWqT", // 1987 Rick Astley
  "5ghIJDpPoe3CfHMGu71E6T", // 1991 Nirvana
  "32OlwWuMpZ6b0aN2RZOeMS", // 2014 Mark Ronson
  "7qiZfU4dY1lWllzX7mPBI3", // 2017 Ed Sheeran
  "0VjIjW4GlUZAMYd2vXMi3b", // 2019 The Weeknd
  "0yLdNVWF3Srea0uzk55zFn", // 2023 Miley Cyrus
];
const byId = new Map(full.map((s) => [s.id, s]));
const test = testIds.map((id) => byId.get(id)).filter(Boolean);

const banner = "// AUTO-GENERATED by hitster/tools/build-songs.mjs - do not edit by hand.\n";
const js =
  banner +
  `window.HITSTER_TEST = ${JSON.stringify(test, null, 2)};\n\n` +
  `window.HITSTER_FULL = ${JSON.stringify(full, null, 2)};\n`;

await writeFile(songsOut, js);

console.log(`kept ${full.length} verified tracks; dropped ${dropped.length} title mismatches`);
if (dropped.length) console.log("dropped:", dropped.map((d) => `${d.artist} - ${d.title} (=> ${d.spotifyTitle})`).join("; "));
console.log(`test deck: ${test.length} cards (${test.map((t) => t.year).join(", ")})`);
if (test.length !== testIds.length) console.log("WARNING: some test ids not found in verified pool");
console.log(`wrote ${songsOut}`);
